name: Monitor JCF Automatizado

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Se ejecuta en automático al inicio de cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
